### ISSUE TITLE
Code examples in Readme or Wiki

### ISSUE THREAD

**Issue by Masken8** [kennethloeffler/anatta#22]
As someone new to entity component systems, it's really hard to understand how to use WorldSmith so I think some examples in the Readme or Wiki would be really nice.

**Comment by kennethloeffler** [comment]
Hi there, 

This project is currently undergoing some intense refactoring (you may check the current progress @ [WorldSmithv2 ](https://github.com/kennethloeffler/WorldSmith/tree/WorldSmithv2)). When this is complete, I will include an API reference as well as a detailed instruction manual in the repository. I expect this to take no more than two weeks longer. 

In the meantime, if you would like to read up on entity systems in general (what they are, how they work, etc.), I highly recommend [Entity Systems are the future of MMOG development](http://t-machine.org/index.php/2007/09/03/entity-systems-are-the-future-of-mmog-development-part-1/), a series of articles by Adam Martin. This should get you up to speed with the terminology and the gist of how this is all supposed to work.

Thank you for your interest! :)

**Comment by Masken8** [comment]
Ok. Thank you for the reply, almost forgot about this issue :)

**Comment by Masken8** [comment]
does 8312f79 mean V2 is complete?

**Comment by Masken8** [comment]
Any update on this?

**Comment by kennethloeffler** [comment]
Currently dogfooding the module/plugin - I’m pretty close to a stable version, hang tight 🤞
